tasks:
  - init: cd /workspace/vulcan-demo/doc && npm install
    command: cd /workspace/vulcan-demo/doc && bash ./generate.sh && ./node_modules/.bin/docsify serve -p 3001 .
    openMode: tab-after
    name: Document server
  - init: npm install
    command: ./node_modules/.bin/vulcan start --watch
    openMode: tab-after
    name: Vulcan
ports:
  - name: Vulcan server
    port: 3000
    onOpen: ignore
    visibility: public
  - name: Document
    port: 3001
    onOpen: open-preview
    visibility: private
